// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAir-d-cJVIoDYnA-dC5DLbLb02Lg_NctQ',
    appId: '1:476760291757:web:6c970369bc6dacea62c924',
    messagingSenderId: '476760291757',
    projectId: 'messenger-app-crackers',
    authDomain: 'messenger-app-crackers.firebaseapp.com',
    storageBucket: 'messenger-app-crackers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIFLayVslDRzxm5_pc47J7Rc_lvBBIrFQ',
    appId: '1:476760291757:android:62e9f792d20086e762c924',
    messagingSenderId: '476760291757',
    projectId: 'messenger-app-crackers',
    storageBucket: 'messenger-app-crackers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtvl3wvESRkUPEU_vMjFuMFmOOVxLfU7Y',
    appId: '1:476760291757:ios:79936ba75704f5e462c924',
    messagingSenderId: '476760291757',
    projectId: 'messenger-app-crackers',
    storageBucket: 'messenger-app-crackers.appspot.com',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtvl3wvESRkUPEU_vMjFuMFmOOVxLfU7Y',
    appId: '1:476760291757:ios:cf32a00675ed4b1e62c924',
    messagingSenderId: '476760291757',
    projectId: 'messenger-app-crackers',
    storageBucket: 'messenger-app-crackers.appspot.com',
    iosBundleId: 'com.example.messengerApp.RunnerTests',
  );
}
